"""Seed demo workspace: projects, tasks, and sample attachments covering
every supported preview type (docx, xlsx, pptx, pdf, csv, json, code,
markdown, text, zip, png, wav).

Run:  python -m app.seed [--force]
"""
import io
import json
import struct
import sys
import wave
import zipfile
import zlib
from datetime import date, datetime, timedelta

from .database import Base, SessionLocal, UPLOAD_DIR, engine, init_db
from .models import FileAttachment, Project, Task


# ------------------------------------------------------------ file builders
def make_docx() -> bytes:
    import docx

    doc = docx.Document()
    doc.add_heading("Q3 Product Review", level=1)
    doc.add_paragraph("Prepared by the product team. This document summarises progress "
                      "against the Q3 roadmap and lists risks for the coming sprint.")
    doc.add_heading("Key metrics", level=2)
    table = doc.add_table(rows=4, cols=2)
    data = [("Metric", "Value"), ("Activation rate", "62%"),
            ("Weekly active users", "18,400"), ("Churn", "2.1%")]
    for i, (a, b) in enumerate(data):
        table.rows[i].cells[0].text = a
        table.rows[i].cells[1].text = b
    doc.add_paragraph("Next steps: ship the onboarding revamp and re-measure in two weeks.")
    buf = io.BytesIO()
    doc.save(buf)
    return buf.getvalue()


def make_xlsx() -> bytes:
    from openpyxl import Workbook

    wb = Workbook()
    ws = wb.active
    ws.title = "Budget"
    ws.append(["Category", "Planned", "Actual", "Delta"])
    for row in [("Engineering", 120000, 115400, 4600),
                ("Marketing", 45000, 51200, -6200),
                ("Design", 30000, 28750, 1250),
                ("Infra", 22000, 22980, -980)]:
        ws.append(list(row))
    ws2 = wb.create_sheet("Headcount")
    ws2.append(["Team", "Members"])
    ws2.append(["Backend", 6])
    ws2.append(["Frontend", 4])
    ws2.append(["QA", 3])
    buf = io.BytesIO()
    wb.save(buf)
    return buf.getvalue()


def make_pptx() -> bytes:
    from pptx import Presentation
    from pptx.util import Inches

    prs = Presentation()
    slide = prs.slides.add_slide(prs.slide_layouts[0])
    slide.shapes.title.text = "Sprint 14 Demo"
    slide.placeholders[1].text = "Taskie — agentic task management"
    slide2 = prs.slides.add_slide(prs.slide_layouts[1])
    slide2.shapes.title.text = "Highlights"
    body = slide2.placeholders[1].text_frame
    body.text = "Recommendation engine live"
    body.add_paragraph().text = "Auto-planner schedules the backlog"
    body.add_paragraph().text = "File preview for every format"
    buf = io.BytesIO()
    prs.save(buf)
    return buf.getvalue()


def make_pdf() -> bytes:
    """Build a minimal, valid, browser-renderable PDF with a little text."""
    lines = [
        "BT /F1 22 Tf 72 720 Td (Taskie Sample Report) Tj ET",
        "BT /F1 12 Tf 72 680 Td (This PDF was generated by the seed script.) Tj ET",
        "BT /F1 12 Tf 72 660 Td (Browsers render it inline via the preview pane.) Tj ET",
    ]
    stream = "\n".join(lines).encode()
    objects = [
        b"<</Type/Catalog/Pages 2 0 R>>",
        b"<</Type/Pages/Kids[3 0 R]/Count 1>>",
        b"<</Type/Page/Parent 2 0 R/MediaBox[0 0 612 792]/Contents 4 0 R"
        b"/Resources<</Font<</F1 5 0 R>>>>>>",
        b"<</Length " + str(len(stream)).encode() + b">>stream\n" + stream + b"\nendstream",
        b"<</Type/Font/Subtype/Type1/BaseFont/Helvetica>>",
    ]
    out = io.BytesIO()
    out.write(b"%PDF-1.4\n")
    offsets = []
    for i, obj in enumerate(objects, 1):
        offsets.append(out.tell())
        out.write(f"{i} 0 obj\n".encode() + obj + b"\nendobj\n")
    xref_pos = out.tell()
    out.write(f"xref\n0 {len(objects) + 1}\n".encode())
    out.write(b"0000000000 65535 f \n")
    for off in offsets:
        out.write(f"{off:010d} 00000 n \n".encode())
    out.write(f"trailer\n<</Size {len(objects) + 1}/Root 1 0 R>>\nstartxref\n{xref_pos}\n%%EOF".encode())
    return out.getvalue()


def make_png() -> bytes:
    """64x64 gradient PNG, pure stdlib."""
    w = h = 64
    raw = b""
    for y in range(h):
        raw += b"\x00"  # filter: none
        for x in range(w):
            raw += bytes([99 + x * 2, 102, 241 - y * 2, 255])

    def chunk(tag, data):
        c = struct.pack(">I", len(data)) + tag + data
        return c + struct.pack(">I", zlib.crc32(tag + data) & 0xFFFFFFFF)

    ihdr = struct.pack(">IIBBBBB", w, h, 8, 6, 0, 0, 0)
    return (b"\x89PNG\r\n\x1a\n"
            + chunk(b"IHDR", ihdr)
            + chunk(b"IDAT", zlib.compress(raw))
            + chunk(b"IEND", b""))


def make_wav() -> bytes:
    """1 second 440Hz tone."""
    buf = io.BytesIO()
    with wave.open(buf, "wb") as wf:
        wf.setnchannels(1)
        wf.setsampwidth(2)
        wf.setframerate(8000)
        import math
        frames = b"".join(
            struct.pack("<h", int(12000 * math.sin(2 * math.pi * 440 * i / 8000)))
            for i in range(8000)
        )
        wf.writeframes(frames)
    return buf.getvalue()


def make_zip() -> bytes:
    buf = io.BytesIO()
    with zipfile.ZipFile(buf, "w") as zf:
        zf.writestr("release-notes.txt", "v1.0.0 — initial public release of Taskie.\n")
        zf.writestr("assets/logo.svg", '<svg xmlns="http://www.w3.org/2000/svg"/>')
        zf.writestr("data/metrics.json", json.dumps({"stars": 128, "installs": 4300}))
    return buf.getvalue()


SAMPLE_FILES = [
    ("Q3-product-review.docx", make_docx,
     "application/vnd.openxmlformats-officedocument.wordprocessingml.document"),
    ("budget-2025.xlsx", make_xlsx,
     "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet"),
    ("sprint-demo.pptx", make_pptx,
     "application/vnd.openxmlformats-officedocument.presentationml.presentation"),
    ("sample-report.pdf", make_pdf, "application/pdf"),
    ("logo.png", make_png, "image/png"),
    ("notification.wav", make_wav, "audio/wav"),
    ("release-bundle.zip", make_zip, "application/zip"),
    ("metrics.csv", lambda: b"Week,Completed,Overdue\n1,5,2\n2,8,1\n3,6,0\n4,9,1\n", "text/csv"),
    ("notes.md", lambda: (
        b"# Standup notes\n\n- Ship **file preview** for all formats\n"
        b"- Agent recommends priorities daily\n- [ ] Draft release post\n"), "text/markdown"),
    ("deploy.py", lambda: (
        b"import subprocess\n\ndef deploy(env='prod'):\n"
        b'    """Run the deployment pipeline."""\n'
        b"    subprocess.check_call(['make', f'deploy-{env}'])\n"), "text/x-python"),
    ("config.json", lambda: json.dumps({"app": "taskie", "agent": {"enabled": True},
                                        "themes": ["dark", "light"]}, indent=2).encode(),
     "application/json"),
]


# ------------------------------------------------------------------ seeding
def seed(force: bool = False):
    if force:
        Base.metadata.drop_all(engine)
    init_db()
    db = SessionLocal()
    try:
        if db.query(Task).count() > 0 and not force:
            print("Database already has tasks — skipping seed (use --force to reset).")
            return

        today = date.today()
        p1 = Project(name="Product Launch", description="Everything for the v1.0 launch", color="#6366f1")
        p2 = Project(name="Marketing", description="Growth and content", color="#10b981")
        p3 = Project(name="Engineering", description="Platform and infra", color="#f59e0b")
        db.add_all([p1, p2, p3])
        db.flush()

        tasks = [
            Task(project_id=p1.id, title="Finalise launch checklist", description="Review go/no-go items with stakeholders.",
                 status="in_progress", priority="high", due_date=today, estimated_minutes=90,
                 progress=60, tags="launch,ops", created_at=datetime.utcnow() - timedelta(days=5)),
            Task(project_id=p1.id, title="Write release notes", description="Summarise changes since v0.9 for the changelog.",
                 status="todo", priority="high", due_date=today + timedelta(days=2), estimated_minutes=45,
                 progress=0, tags="docs", created_at=datetime.utcnow() - timedelta(days=4)),
            Task(project_id=p1.id, title="Record demo video", description="3-minute walkthrough for the landing page.",
                 status="todo", priority="medium", due_date=today + timedelta(days=5), estimated_minutes=120,
                 progress=0, tags="marketing", created_at=datetime.utcnow() - timedelta(days=3)),
            Task(project_id=p2.id, title="Publish launch blog post", description="Coordinate with design on cover image.",
                 status="todo", priority="critical", due_date=today - timedelta(days=2), estimated_minutes=180,
                 progress=30, tags="content", created_at=datetime.utcnow() - timedelta(days=9)),
            Task(project_id=p2.id, title="Set up analytics dashboards", description="Track activation and funnel events.",
                 status="todo", priority="medium", estimated_minutes=60,
                 progress=0, tags="analytics", created_at=datetime.utcnow() - timedelta(days=2)),
            Task(project_id=p2.id, title="Draft newsletter", description="Announcement email to 4.3k subscribers.",
                 status="done", priority="medium", due_date=today - timedelta(days=1), estimated_minutes=40,
                 progress=100, tags="content",
                 created_at=datetime.utcnow() - timedelta(days=6), completed_at=datetime.utcnow() - timedelta(days=1)),
            Task(project_id=p3.id, title="Fix file upload timeout on slow networks", description="Retry logic + progress events.",
                 status="in_progress", priority="critical", due_date=today + timedelta(days=1), estimated_minutes=150,
                 progress=35, tags="bug,backend", created_at=datetime.utcnow() - timedelta(days=6)),
            Task(project_id=p3.id, title="Migrate CI to new runners", description="Cut pipeline time below 5 minutes.",
                 status="todo", priority="low", due_date=today + timedelta(days=10), estimated_minutes=240,
                 progress=0, tags="infra", created_at=datetime.utcnow() - timedelta(days=2)),
            Task(project_id=p3.id, title="Review agent scoring heuristics", description="Validate priority weights against real usage.",
                 status="blocked", priority="high", due_date=today + timedelta(days=3), estimated_minutes=90,
                 progress=20, tags="ai,review", created_at=datetime.utcnow() - timedelta(days=7)),
            Task(project_id=p3.id, title="Ship dark mode polish", description="Contrast fixes on the planner view.",
                 status="done", priority="low", due_date=today - timedelta(days=3), estimated_minutes=30,
                 progress=100, tags="ui",
                 created_at=datetime.utcnow() - timedelta(days=8), completed_at=datetime.utcnow() - timedelta(days=3)),
            Task(project_id=p1.id, title="Prepare investor update", description="Metrics deck + narrative for the monthly update.",
                 status="todo", priority="high", due_date=today + timedelta(days=4), estimated_minutes=120,
                 progress=0, tags="strategy", created_at=datetime.utcnow() - timedelta(days=1)),
        ]
        db.add_all(tasks)
        db.commit()

        # assign tasks across the demo team (a couple stay unassigned on purpose)
        from .models import User
        users = {u.username: u for u in db.query(User).all()}
        demo = users.get("demo")
        ava = users.get("ava")
        ben = users.get("ben")
        assignments = [
            (tasks[0], demo), (tasks[1], demo), (tasks[2], None),
            (tasks[3], ava), (tasks[4], ava), (tasks[5], ava),
            (tasks[6], demo), (tasks[7], ben), (tasks[8], ben),
            (tasks[9], ben), (tasks[10], None),
        ]
        for t, u in assignments:
            if u:
                t.assignee_id = u.id
        db.commit()

        # attach sample files across a few tasks
        plan = [
            (tasks[0], ["Q3-product-review.docx", "sample-report.pdf", "notes.md"]),
            (tasks[3], ["metrics.csv", "logo.png"]),
            (tasks[4], ["budget-2025.xlsx", "config.json"]),
            (tasks[6], ["deploy.py", "release-bundle.zip"]),
            (tasks[2], ["sprint-demo.pptx", "notification.wav"]),
        ]
        by_name = {name: (builder, mime) for name, builder, mime in SAMPLE_FILES}
        for task, filenames in plan:
            for fname in filenames:
                builder, mime = by_name[fname]
                data = builder()
                ext = "." + fname.rsplit(".", 1)[-1].lower()
                stored = f"seed-{task.id}-{fname.replace(' ', '_')}"
                (UPLOAD_DIR / stored).write_bytes(data)
                db.add(FileAttachment(task_id=task.id, filename=fname, stored_name=stored,
                                      mime_type=mime, extension=ext, size=len(data)))
        db.commit()

        # seed shared project chats
        from .models import ProjectMessage
        if db.query(ProjectMessage).count() == 0:
            now = datetime.utcnow()
            messages = [
                (p1, demo, "Kickoff: launch checklist is live — grab your items!", now - timedelta(hours=5)),
                (p1, ava, "Blog post draft is 80% there. Cover image pending.", now - timedelta(hours=4)),
                (p1, ben, "Upload timeout fix needs a reviewer — who's free today?", now - timedelta(hours=2)),
                (p2, ava, "Analytics events are firing; dashboard link in the shared files.", now - timedelta(hours=6)),
                (p2, demo, "Newsletter went out — 41% open rate 🎉", now - timedelta(hours=3)),
                (p3, ben, "CI migration branch is up. Pipeline down to 6min already.", now - timedelta(hours=7)),
                (p3, demo, "Agent scoring review is blocked on usage data — @Ava can you export it?", now - timedelta(hours=1)),
            ]
            for proj, user, body, ts in messages:
                db.add(ProjectMessage(project_id=proj.id, user_id=user.id if user else None,
                                      body=body, created_at=ts))

            # a couple of project-level shared files
            plan = [(p2, "metrics.csv"), (p3, "deploy.py")]
            by_name = {name: (builder, mime) for name, builder, mime in SAMPLE_FILES}
            for proj, fname in plan:
                builder, mime = by_name[fname]
                data = builder()
                stored = f"seed-proj-{proj.id}-{fname}"
                (UPLOAD_DIR / stored).write_bytes(data)
                db.add(FileAttachment(task_id=None, project_id=proj.id, filename=fname,
                                      stored_name=stored, mime_type=mime,
                                      extension="." + fname.rsplit(".", 1)[-1], size=len(data),
                                      uploaded_by=demo.id if demo else None))
            db.commit()

        print(f"Seeded {db.query(Task).count()} tasks, {db.query(FileAttachment).count()} files, "
              f"{db.query(ProjectMessage).count()} messages, {db.query(Project).count()} projects.")
    finally:
        db.close()


if __name__ == "__main__":
    seed(force="--force" in sys.argv)
